version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app/models:/app/models

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - api